# [package]
# name = "airsign_dtw_experiments"
# version = "0.1.0"
# edition = "2021"

[workspace]

resolver = "2"

members = [
  "rust_dtw_algorithm",
  "experiments",
]

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
